Update CI.yaml

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -38,7 +38,7 @@ jobs:
       - name: Set MSBuild env
         uses: microsoft/setup-msbuild@main
       - name: Get dependencies
-        run: choco install meson ninja || echo "Fail"
+        run: pip install meson ninja || echo "Fail"
       - name: Checkout submodules
         shell: bash
         run: |
